version: "3.8"
services:
  app:
    # image:dor93/version-alert:latest
    build: .
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - server:/app/server
      - client:/app/client
    environment:
      - NODE_ENV=development

volumes:
  server:
  client:
